feat: add checkbox component
ansopedia/web-app pull request #11
Opened 2024-04-05 07:24 UTC by Meet-Kalani

2024-04-05 10:09 UTC, sanjaysah101 requested changes

2024-04-05 10:09 UTC, sanjaysah101 commented on src/components/ui/Checkbox/Checkbox.tsx
> +};
Remove useRef, & optimize id. 

## Here the final components

```

import { FC, useId } from 'react';
import style from './checkbox.module.scss';

interface InputProps extends React.ComponentPropsWithRef<'input'> {
  label: string;
  checked?: boolean;
  disabled?: boolean;
}

const Checkbox: FC<InputProps> = ({ label, ...props }: InputProps) => {
  const id = `${useId()}-${label}`;

  return (
    <div className={style['checkbox-container']}>
      <input type="checkbox" className={style.checkbox} id={id} onChange={props.onChange} {...props} />
      <label htmlFor={id} className={style.label}>
        {label}
      </label>
    </div>
  );
};

export default Checkbox;

```

2024-04-05 10:09 UTC, sanjaysah101 commented on src/app/(home)/page.tsx
>      </>
Remove Checkbox component from landing page.

2024-04-05 10:09 UTC, sanjaysah101 commented on src/styles/_constants.scss
> +$color-disabled: #E5E5E6;/* Disable field color */
Rename `color-disabled `to `$color-gray-50`

2024-04-05 10:09 UTC, sanjaysah101 commented on src/components/ui/Checkbox/checkbox.svg
Remove chekbox.svg if it is not required

2024-04-05 19:06 UTC, sanjaysah101 submitted a review, later dismissed

2024-04-05 19:11 UTC, ansopedia approved these changes

2024-04-05 19:12 UTC, sanjaysah101 approved these changes

2024-04-05 19:12 UTC, sanjaysah101 approved these changes

2024-04-06 07:42 UTC, ansopedia approved these changes

2024-04-06 07:42 UTC, merged

2024-04-06 07:44 UTC, ansopedia commented
Close #8